### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by Lasciarti** [Fraunhofer-AISEC/trusted-connector#142]
When starting Docker, it prompts that the certificate has expired on January 27, 2024. May I ask if it's possible to update the certificate or give me some suggestions for making my own certificate. Thanks!

**Comment by gbrost** [comment]
@milux Can you take this, please?

**Comment by gbrost** [comment]
If you want to use our DAPS-instance, you can request a set of current certificates here:
daps-certificates-request@aisec.fraunhofer.de

We will then provide those. 

We also need to update the project demo certificates. Sorry for that.

**Comment by milux** [comment]
Please note that, although you may ask for certificates from our official DAPS (`daps.aisec.fraunhofer.de`), all demos except one (going to fix this ASAP) are pointing to our development DAPS (`daps-dev.aisec...`).
This is intended, as the "secret" key material of the demos is publicly known and accessible via this repo to everyone, thus not suitable for any semi-productive prototypes equipped with "official" certificates.
We may release a new TC minor release with fixed examples today or a little later, please stay tuned.
