### ISSUE TITLE
The Provider UI does not refresh connections in a proper way

### ISSUE THREAD

**Issue by Olatz1** [Fraunhofer-AISEC/trusted-connector#26]
### Steps to reproduce the behavior
1. Start consumer and provider
2. Open the UI in the provider side
2. Stop the consumer
3. Start the consumer again

### Expected behavior
In the UI the connection to the consumer is shown only when it's running and configured to connect to it.

### Actual behavior
In the provider UI a connection to the consumer is still shown when the consumer is stopped.
In the provider UI two connections to the same consumer are shown when the consumer is running again

**Comment by gbrost** [comment]
Does not work any more with current implementation. We need to re-add this as a feature for IDSCPv2

**Comment by milux** [comment]
This will very likely require changes to `idscp2-jvm`, especially `camel-idscp2`.
Will look into it soon.

**Comment by milux** [comment]
Should be solved by now, release going to follow.
