### ISSUE TITLE
Upgrade to latest Camel version

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/trusted-connector#50]
And check what is broken, and if we need it.

**Comment by milux** [comment]
Already tried that, two things get broken:
- Route XML export (required for the editor that never really worked anyway)
- Metrics Beans stuff (Number of (un)successful Exchanges, active routes, disabled routes, route duration, etc.) --> Could be replaced by an interceptor, if it's still required.

**Comment by milux** [comment]
Done, broken UI stuff has been removed.
