### ISSUE TITLE
Link to examples in documentation page broken

### ISSUE THREAD

**Issue by gbrost** [Fraunhofer-AISEC/trusted-connector#74]
### Steps to reproduce the behavior
Click on the example download link [here]:(https://industrial-data-space.github.io/trusted-connector-documentation/docs/getting_started/)

### Expected behavior
Zip archive is downloaded

### Actual behavior
Links to not existing file. We need to define how to deal with versioning. Should we hardlink to specific versions?

**Comment by redingjl** [comment]
Updated the link, points now to latest
