### ISSUE TITLE
How do I use trusted-connector?

### ISSUE THREAD

**Issue by xiemingyuan996** [Fraunhofer-AISEC/trusted-connector#84]
Hello, I have configured a connector and logged into the Web console following the official tutorial:
https://industrial-data-space.github.io/trusted-connector-documentation/docs/getting_started/

![image](https://user-images.githubusercontent.com/96281915/146501991-ce8ef68f-eb32-4470-a872-2bcd4fc09861.png)
What should I do after that? Can I provide a complete tutorial (how to communicate between connectors, how to configure usage policies, etc.) or relevant documents?

Looking forward to your reply. Thank you！

**Comment by gbrost** [comment]
You are right. We restructured our documentation and are now missing some links on how to find the documentation how to connector between connector instances etc. We will have a look into that.

**Comment by redingjl** [comment]
We have updated the documentation some time ago, sorry for responding late here.
There is also a new section about using the connector with a short explanation and references to other parts of the documentation.
